### ISSUE TITLE
something inside causes 500 error?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/legacysurvey-backend#3]
on https://frontend.staging.odahub.io/mmoda/ I put Crab and larger time (maybe it's not used).

backend ends up querying 'https://www.legacysurvey.org/viewer/fits-cutout?ra=83.633212&dec=22.01446&size=1296000&layer=ls-dr9&pixscale=0.0002777777777777778&bands=g'

which returns 500

Not sure whom to ask.

where does Legacysurvey_tap.ipynb come from? Can it be in a submodule, so that the reference to renku repository (hopefully) is preserved? That would help smartsky too!

**Comment by dsavchenko** [comment]
Seems like the cause of this is that Crab is outside of survey coverage. Such situations should be treated in astroquery module

Concerning Legacysurvey_tap.ipynb I used to get it from renku (https://github.com/oda-hub/legacysurvey-backend/blob/main/get_nb.sh). But then I edited it in-place and pushed changed version here. Maybe submodule is way to go to not mess up things like that.

**Comment by volodymyrss** [comment]
Yeah.

Also, the error response should contain some useful information. Could we channel (part of it?) to the user? Plugin would have to do that.

**Comment by dsavchenko** [comment]
We can, of course. Again, it would be better if astroquery produce a meaningful error for such situations. Then it can be channelled. The server response is misleading, one may check if the point is inside the coverage prior to the request, if a coverage map is available somewhere, but I haven't found it.

**Comment by burnout87** [comment]
I tried and succeeded in reproducing the very same error from the legacy survey.

For the `get_images` method a FileContainer object is returned from astroquery, when it should be a `HDUList` as specified in the doc: [https://astroquery.readthedocs.io/en/latest/api.html?highlight=get_images#get-images](https://astroquery.readthedocs.io/en/latest/api.html?highlight=get_images#get-images).

This can be easily changed, as well as handled the case where nothing is returned as is the case of this issue.

I will provide a PR with the required changes.

**Comment by burnout87** [comment]
[](https://github.com/oda-hub/astroquery/pull/10) handles this issue, has this been re-verified if a better message is now returned?

**Comment by volodymyrss** [comment]
@dsavchenko ?

**Comment by dsavchenko** [comment]
Yes, now it produces `'NoResultsWarning'` with the message `'HTTP Error 500: Internal Server Error - Problem retrieving the file at the url: https://www.legacysurvey.org/viewer/fits-cutout?ra=83.633083333333&dec=22.0145&size=360&layer=ls-dr9&pixscale=1.0&bands=g'` which is ok.
