### ISSUE TITLE
some other 500 error?

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/legacysurvey-backend#5]
This happens now:

![image](https://user-images.githubusercontent.com/3909535/154318388-6c3ef985-006b-48ca-b1a8-185a2d3769d3.png)

I think it means the notebook is not the right one. Can you point me to the notebook on renku which is the good one?

Deployed with https://github.com/oda-hub/nb2workflow#deploys-a-service

**Comment by dsavchenko** [comment]
The point is in the galactic plane, so this is expected.

Another question here is why the plugin in staging doesn't raise the proper exception for it.

**Comment by dsavchenko** [comment]
Now I see. This is produced by some previous version of notebook. The proper one is in this repo.
And it is also built with previous version of astroquery module

**Comment by volodymyrss** [comment]
ok, I did not have it. I will deploy.

**Comment by dsavchenko** [comment]
We are still out-of-sync with renku repo here. 
But maybe let's postpone it for the actual full implementation of the renku-based workflows?

**Comment by volodymyrss** [comment]
I do something after lunch.

**Comment by volodymyrss** [comment]
I updated to [this one](https://renkulab.io/gitlab/dsavchenko/oda-sdss/-/blob/master/Legacysurvey_tap.ipynb)

Now this 
![image](https://user-images.githubusercontent.com/3909535/154321194-6ea7cda8-0c95-4e78-b612-fa2b806cdc82.png)

**Comment by volodymyrss** [comment]
the notebook actually completed successfully. 

Note that you can view the exectured notebooks like this:

http://localhost:8000/trace/list
http://localhost:8000/trace/nb2w-y8cplmvn
http://localhost:8000/trace/nb2w-y8cplmvn/Legacysurvey_tap

edit: the error is in the plugin

```python
ERROR:cdci_data_analysis.flask_app.dispatcher_query:
Traceback (most recent call last):
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/instrument.py", line 309, in run_query
    query_out = query_obj.run_query(self, out_dir, job, run_asynch,
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/queries.py", line 642, in run_query
    query_out = self.get_query_products(instrument,job,run_asynch, query_type=query_type, logger=logger, config=config,scratch_dir=scratch_dir,sentry_client=sentry_client,api=api)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/cdci_data_analysis/analysis/queries.py", line 508, in get_query_products
    prod_list = self.build_product_list(instrument,res, scratch_dir,api=api)
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/dispatcher_plugin_legacysurvey/queries.py", line 100, in build_product_list
    image = LSImageProduct(imfits_head,
  File "/pyenv/versions/3.8.5/lib/python3.8/site-packages/dispatcher_plugin_legacysurvey/products.py", line 47, in __init__
    data_unit = NumpyDataUnit(data, header, hdu_type='image', name='image')
  File "/src/oda-api/oda_api/data_products.py", line 187, in __init__
    self._check_dict(data_header)
  File "/src/oda-api/oda_api/data_products.py", line 231, in _check_dict
    raise RuntimeError('object is not not dict')
RuntimeError: object is not not dict
```

It's the latest plugin, 894cd41

**Comment by dsavchenko** [comment]
https://renkulab.io/gitlab/vladimir.savchenko/oda-sdss/-/merge_requests/5 will fix 'object is not dict'

**Comment by dsavchenko** [comment]
The problem with Simbad is not obvious. But Simbad is not needed for the service. Wait a bit, I will clean up the nb from unnecessary things

**Comment by volodymyrss** [comment]
> The problem with Simbad is not obvious. But Simbad is not needed for the service. Wait a bit, I will clean up the nb from unnecessary things

that was just older version I think. Once I moved to your fork it disappeared. It also is not there after last merge.

Now I get this:

![image](https://user-images.githubusercontent.com/3909535/154326136-2d200f71-5b09-4fb8-a4cf-6a9995600220.png)

**Comment by dsavchenko** [comment]
That's ok, since the frontend is not yet updated to the new Bokeh in staging.

**Comment by volodymyrss** [comment]
Ok, I suspected so. This one then https://github.com/oda-hub/frontend-astrooda/pull/130
